/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsernameImport } from './routes/username'
import { Route as SandwichImport } from './routes/sandwich'
import { Route as AnimationImport } from './routes/animation'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UsernameRoute = UsernameImport.update({
  id: '/username',
  path: '/username',
  getParentRoute: () => rootRoute,
} as any)

const SandwichRoute = SandwichImport.update({
  id: '/sandwich',
  path: '/sandwich',
  getParentRoute: () => rootRoute,
} as any)

const AnimationRoute = AnimationImport.update({
  id: '/animation',
  path: '/animation',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/animation': {
      id: '/animation'
      path: '/animation'
      fullPath: '/animation'
      preLoaderRoute: typeof AnimationImport
      parentRoute: typeof rootRoute
    }
    '/sandwich': {
      id: '/sandwich'
      path: '/sandwich'
      fullPath: '/sandwich'
      preLoaderRoute: typeof SandwichImport
      parentRoute: typeof rootRoute
    }
    '/username': {
      id: '/username'
      path: '/username'
      fullPath: '/username'
      preLoaderRoute: typeof UsernameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animation': typeof AnimationRoute
  '/sandwich': typeof SandwichRoute
  '/username': typeof UsernameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animation': typeof AnimationRoute
  '/sandwich': typeof SandwichRoute
  '/username': typeof UsernameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/animation': typeof AnimationRoute
  '/sandwich': typeof SandwichRoute
  '/username': typeof UsernameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animation' | '/sandwich' | '/username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animation' | '/sandwich' | '/username'
  id: '__root__' | '/' | '/animation' | '/sandwich' | '/username'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimationRoute: typeof AnimationRoute
  SandwichRoute: typeof SandwichRoute
  UsernameRoute: typeof UsernameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimationRoute: AnimationRoute,
  SandwichRoute: SandwichRoute,
  UsernameRoute: UsernameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/animation",
        "/sandwich",
        "/username"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/animation": {
      "filePath": "animation.tsx"
    },
    "/sandwich": {
      "filePath": "sandwich.tsx"
    },
    "/username": {
      "filePath": "username.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
